name: Spring Sample Web App CI

on: 
  push:
    paths:
    - 'spring/fluentforms-sample-web-jersey-app/**'
    - 'spring/fluentforms-sample-webmvc-app/**'
    - '.github/workflows/spring-sample-web-apps-ci.yml'
  workflow_dispatch:
    
jobs:
  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        java: [ 21 ]
        experimental: [false]
        include:
          - java: 25
            experimental: true

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build Sample Jersey Web App with Maven
      run: mvn -B install -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-sample-web-jersey-app
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build Sample Web MVC App with Maven
      run: mvn -B install -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-sample-webmvc-app
      env:
        GITHUB_TOKEN: ${{ github.token }}

#
#
#    - name: Publish Sample Web App to GitHub Packages Apache Maven
#      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-sample-web-app
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
  