name: Spring Boot WebMVC Starter CI

on: 
  push:
    paths:
    - 'spring/fluentforms-spring-boot-**'
    - '.github/workflows/spring-boot-webmvc-starter-ci.yml'
  workflow_dispatch:
    
jobs:
  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        java: [ 25 ]
        experimental: [false]
#        include:
#          - java: 25
#            experimental: true

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build AutoConfigure with Maven
      run: mvn -B install -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-spring-boot-autoconfigure
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build AutoConfigure with Maven
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/tags/*') &&  !matrix.experimental # Only run on main branch or tags and non-experimental
      run: mvn -B deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-spring-boot-autoconfigure # skip tests because they were run in the previous step
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish Starter to GitHub Packages Apache Maven
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/tags/*') &&  !matrix.experimental # Only run on main branch or tags and non-experimental
      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-spring-boot-starter
      env:
       GITHUB_TOKEN: ${{ github.token }}
  